### ISSUE TITLE
Intermittent error in oozie-setup

### ISSUE THREAD

**Issue by marvi** [MetaCenterCloudPuppet/cesnet-oozie#3]
Environment: CDH 6.1, Centos 7.6, RPM

During copying of sharelib it fails when looking for 
`/usr/lib/oozie/oozie-sharelib-yarn/share/lib/spark/spark-catalyst_2.11-2.4.0-cdh6.1.0.jar;5cdbde11` owned by root:root with permission 600. 

Some kind of temp file created by Hadoop FS API? It's not in the RPM.

Removing the file and running again recreated it and it failed again. Tried it a few more times and it suddenly worked. Never got the error when running oozie-setup outside Puppet, but since the error is intermittent I can't be sure if it is Puppet related.

**Comment by valtri** [comment]
It could have been caused by the timeout of the puppet exec - the ```oozie-setup sharelib``` command takes some time in the recent oozie versions. The upcoming version 0.13.0 increase the timeout.
